//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace Primavera.Lithium.Faturacao.Client.Console.Configuration
{
    #region Code

    #region Public Classes

    /// <summary>
    /// Defines the base class for the configuration used by the application.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public abstract partial class ApplicationConfigurationBase
    {
        #region Code

        #region Public Properties

        /// <summary>
        /// Gets or sets the service Web API base URI.
        /// </summary>
        [SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings")]
        public virtual string ServiceBaseUri
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the Identity Server base URI.
        /// </summary>
        [SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings")]
        public virtual string IdentityServerBaseUri
        {
            get;
            set;
        }

        #endregion

        #region Protected Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicationConfigurationBase"/> class.
        /// </summary>
        protected ApplicationConfigurationBase()        
        {
            // Set default values

            this.SetDefaultValues();
        }

        #endregion

        #region Protected Methods

        /// <summary>
        /// Sets the default values.
        /// </summary>
        /// <remarks>
        /// This method should be overridden to set the default values of properties.
        /// </remarks>
        protected virtual void SetDefaultValues()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// Defines the configuration used by the application.
    /// </summary>
    /// <seealso cref="ApplicationConfigurationBase" />
    [GeneratedCode("Lithium", "2.0")]
    public partial class ApplicationConfiguration : ApplicationConfigurationBase
    {
        #region Code

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicationConfiguration"/> class.
        /// </summary>
        public ApplicationConfiguration()        
            : base()
        {
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
