//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;

namespace Primavera.Lithium.Faturacao.WebApi.Controllers
{
    #region Code

    #region Internal Classes

    /// <summary>
    /// Provides the error codes that can be returned by the Web API.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    internal static partial class ErrorCodes
    {
        #region Code

        #region Internal Constants

        /// <summary>
        /// The request arguments are invalid.
        /// </summary>
        internal const string RequestArgsInvalid = "RequestArgsInvalid";

        /// <summary>
        /// The Amount is required.
        /// </summary>
        internal const string CreateInvoiceAmountRequired = "CreateInvoiceAmountRequired";

        /// <summary>
        /// The WebhooksEvent is required.
        /// </summary>
        internal const string CreateWebhooksEventWebhooksEventRequired = "CreateWebhooksEventWebhooksEventRequired";

        /// <summary>
        /// The Product is required.
        /// </summary>
        internal const string DeleteWebhooksEventProductRequired = "DeleteWebhooksEventProductRequired";

        /// <summary>
        /// The WebhooksEvent is required.
        /// </summary>
        internal const string DeleteWebhooksEventWebhooksEventRequired = "DeleteWebhooksEventWebhooksEventRequired";

        /// <summary>
        /// The Product is required.
        /// </summary>
        internal const string GetWebhooksEventsByProductProductRequired = "GetWebhooksEventsByProductProductRequired";

        /// <summary>
        /// The SubscriptionId is required.
        /// </summary>
        internal const string GetWebhooksEventsForSubscriptionSubscriptionRequired = "GetWebhooksEventsForSubscriptionSubscriptionRequired";

        /// <summary>
        /// The WebhooksSubscription is required.
        /// </summary>
        internal const string SubscribeWebhooksEventWebhooksSubscriptionRequired = "SubscribeWebhooksEventWebhooksSubscriptionRequired";

        /// <summary>
        /// The Subscription is required.
        /// </summary>
        internal const string UnsubscribeWebhooksEventSubscriptionRequired = "UnsubscribeWebhooksEventSubscriptionRequired";

        /// <summary>
        /// The WebhooksEvent is required.
        /// </summary>
        internal const string UnsubscribeWebhooksEventWebhooksEventRequired = "UnsubscribeWebhooksEventWebhooksEventRequired";

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
