//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;

namespace Primavera.Lithium.Faturacao.WebApi.Controllers
{
    #region Code

    #region Internal Classes

    /// <summary>
    /// Provides means to access resource strings.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    internal partial class ValidationResources
    {
        #region Code

        #region Fields

        private static ResourceManager fieldResourceManager;
        private static CultureInfo fieldResourceCulture;

        #endregion

        #region Public Properties

        /// <summary>
        /// Gets the RES_Error_RequestArgsInvalid resource string.
        /// </summary>
        public static string RES_Error_RequestArgsInvalid
        {
            get
            {
                return ResourceManager.GetString("RES_Error_RequestArgsInvalid", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Error_CreateInvoice_Amount_Required resource string.
        /// </summary>
        public static string RES_Error_CreateInvoice_Amount_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Error_CreateInvoice_Amount_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Error_CreateWebhooksEvent_WebhooksEvent_Required resource string.
        /// </summary>
        public static string RES_Error_CreateWebhooksEvent_WebhooksEvent_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Error_CreateWebhooksEvent_WebhooksEvent_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Error_DeleteWebhooksEvent_Product_Required resource string.
        /// </summary>
        public static string RES_Error_DeleteWebhooksEvent_Product_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Error_DeleteWebhooksEvent_Product_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Error_DeleteWebhooksEvent_WebhooksEvent_Required resource string.
        /// </summary>
        public static string RES_Error_DeleteWebhooksEvent_WebhooksEvent_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Error_DeleteWebhooksEvent_WebhooksEvent_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Error_GetWebhooksEventsByProduct_Product_Required resource string.
        /// </summary>
        public static string RES_Error_GetWebhooksEventsByProduct_Product_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Error_GetWebhooksEventsByProduct_Product_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Error_GetWebhooksEventsForSubscription_Subscription_Required resource string.
        /// </summary>
        public static string RES_Error_GetWebhooksEventsForSubscription_Subscription_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Error_GetWebhooksEventsForSubscription_Subscription_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Error_SubscribeWebhooksEvent_WebhooksSubscription_Required resource string.
        /// </summary>
        public static string RES_Error_SubscribeWebhooksEvent_WebhooksSubscription_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Error_SubscribeWebhooksEvent_WebhooksSubscription_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Error_UnsubscribeWebhooksEvent_Subscription_Required resource string.
        /// </summary>
        public static string RES_Error_UnsubscribeWebhooksEvent_Subscription_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Error_UnsubscribeWebhooksEvent_Subscription_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Error_UnsubscribeWebhooksEvent_WebhooksEvent_Required resource string.
        /// </summary>
        public static string RES_Error_UnsubscribeWebhooksEvent_WebhooksEvent_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Error_UnsubscribeWebhooksEvent_WebhooksEvent_Required", Culture);
            }
        }

        #endregion

        #region Internal Properties

        /// <summary>
        /// Gets the resource manager.
        /// </summary>
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (fieldResourceManager == null)
                {
                    fieldResourceManager = new ResourceManager("Primavera.Lithium.Faturacao.WebApi.GeneratedCode.ValidationResources.gen", typeof(ValidationResources).Assembly);
                }
                
                return fieldResourceManager;
            }
        }

        /// <summary>
        /// Gets or sets the culture.
        /// </summary>
        internal static CultureInfo Culture
        {
            get
            {
                return fieldResourceCulture;
            }
            set
            {
                fieldResourceCulture = value;
            }
        }

        #endregion

        #region Internal Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationResources"/> class.
        /// </summary>
        internal ValidationResources()        
        {
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
