//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using Primavera.Hydrogen.ComponentModel.DataAnnotations;

namespace Primavera.Lithium.Faturacao.Models
{
    #region Code

    #region Public Classes

    /// <summary>
    /// Defines the base class for <see cref="Invoice"/>.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public abstract partial class InvoiceBase
    {
        #region Code

        #region Public Properties

        /// <summary>
        /// The amount to pay.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_Invoice_Amount), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("amount")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_Invoice_Amount_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string Amount
        {
            get;
            set;
        }

        /// <summary>
        /// The ID of the invoice.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_Invoice_Id), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("id")]
        public virtual Guid Id
        {
            get;
            set;
        }

        #endregion

        #region Protected Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="InvoiceBase"/> class.
        /// </summary>
        protected InvoiceBase()        
        {
            // Initialize default values

            this.SetDefaultValues();
        }

        #endregion

        #region Protected Methods

        /// <summary>
        /// Sets the default values.
        /// </summary>
        /// <remarks>
        /// This method should be overridden to set the default values of properties.
        /// </remarks>
        protected virtual void SetDefaultValues()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// The Model for the Invoice.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial class Invoice : InvoiceBase
    {
        #region Code

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="Invoice"/> class.
        /// </summary>
        public Invoice()        
            : base()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// Defines the base class for <see cref="WebhooksEvent"/>.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public abstract partial class WebhooksEventBase
    {
        #region Code

        #region Public Properties

        /// <summary>
        /// Description of an webhook.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksEvent_Description), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("description")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksEvent_Description_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string Description
        {
            get;
            set;
        }

        /// <summary>
        /// Name of the webhook event.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksEvent_Event), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("event")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksEvent_Event_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string Event
        {
            get;
            set;
        }

        /// <summary>
        /// Product that publishes an event.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksEvent_Product), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("product")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksEvent_Product_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string Product
        {
            get;
            set;
        }

        /// <summary>
        /// Required scope to subscribe the event.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksEvent_RequiredScope), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("requiredScope")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksEvent_RequiredScope_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string RequiredScope
        {
            get;
            set;
        }

        #endregion

        #region Protected Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksEventBase"/> class.
        /// </summary>
        protected WebhooksEventBase()        
        {
            // Initialize default values

            this.SetDefaultValues();
        }

        #endregion

        #region Protected Methods

        /// <summary>
        /// Sets the default values.
        /// </summary>
        /// <remarks>
        /// This method should be overridden to set the default values of properties.
        /// </remarks>
        protected virtual void SetDefaultValues()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// Model for the Webhooks Events.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial class WebhooksEvent : WebhooksEventBase
    {
        #region Code

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksEvent"/> class.
        /// </summary>
        public WebhooksEvent()        
            : base()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// Defines the base class for <see cref="WebhooksSubscription"/>.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public abstract partial class WebhooksSubscriptionBase
    {
        #region Code

        #region Public Properties

        /// <summary>
        /// ID of the event being subscribed.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksSubscription_Event), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("event")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksSubscription_Event_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string Event
        {
            get;
            set;
        }

        /// <summary>
        /// Endpoint to where the notification is sent.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksSubscription_NotificationEndpoint), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("notificationEndpoint")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksSubscription_NotificationEndpoint_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string NotificationEndpoint
        {
            get;
            set;
        }

        /// <summary>
        /// Product that produced the event.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksSubscription_Product), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("product")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksSubscription_Product_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string Product
        {
            get;
            set;
        }

        /// <summary>
        /// ID of the Subscriber.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksSubscription_Subscriber), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("subscriber")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksSubscription_Subscriber_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string Subscriber
        {
            get;
            set;
        }

        #endregion

        #region Protected Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksSubscriptionBase"/> class.
        /// </summary>
        protected WebhooksSubscriptionBase()        
        {
            // Initialize default values

            this.SetDefaultValues();
        }

        #endregion

        #region Protected Methods

        /// <summary>
        /// Sets the default values.
        /// </summary>
        /// <remarks>
        /// This method should be overridden to set the default values of properties.
        /// </remarks>
        protected virtual void SetDefaultValues()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// Model for the webhooks subscriptions.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial class WebhooksSubscription : WebhooksSubscriptionBase
    {
        #region Code

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksSubscription"/> class.
        /// </summary>
        public WebhooksSubscription()        
            : base()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// Defines the base class for <see cref="WebhooksSubscriptionDto"/>.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public abstract partial class WebhooksSubscriptionDtoBase
    {
        #region Code

        #region Public Properties

        /// <summary>
        /// ID of the event being subscribed.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksSubscriptionDto_Events), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("events")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksSubscriptionDto_Events_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual IList<string> Events
        {
            get;
            set;
        }

        /// <summary>
        /// Endpoint to where the notification is sent.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksSubscriptionDto_NotificationEndpoint), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("notificationEndpoint")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksSubscriptionDto_NotificationEndpoint_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string NotificationEndpoint
        {
            get;
            set;
        }

        /// <summary>
        /// Product that produced the event.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksSubscriptionDto_Product), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("product")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksSubscriptionDto_Product_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string Product
        {
            get;
            set;
        }

        /// <summary>
        /// ID of the Subscriber.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksSubscriptionDto_Subscriber), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("subscriber")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksSubscriptionDto_Subscriber_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string Subscriber
        {
            get;
            set;
        }

        #endregion

        #region Protected Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksSubscriptionDtoBase"/> class.
        /// </summary>
        protected WebhooksSubscriptionDtoBase()        
        {
            // Initialize list properties

            this.Events = new List<string>();

            // Initialize default values

            this.SetDefaultValues();
        }

        #endregion

        #region Protected Methods

        /// <summary>
        /// Sets the default values.
        /// </summary>
        /// <remarks>
        /// This method should be overridden to set the default values of properties.
        /// </remarks>
        protected virtual void SetDefaultValues()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// Webhooks SubscriptionDto.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial class WebhooksSubscriptionDto : WebhooksSubscriptionDtoBase
    {
        #region Code

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksSubscriptionDto"/> class.
        /// </summary>
        public WebhooksSubscriptionDto()        
            : base()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// Defines the base class for <see cref="WebhooksEventLog"/>.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public abstract partial class WebhooksEventLogBase
    {
        #region Code

        #region Public Properties

        /// <summary>
        /// The number os attempts to send the webhooks event to the subscriber.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksEventLog_Attempts), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("attempts")]
        public virtual int Attempts
        {
            get;
            set;
        }

        /// <summary>
        /// Event being sent.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksEventLog_Event), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("event")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksEventLog_Event_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string Event
        {
            get;
            set;
        }

        /// <summary>
        /// The subscriber to which the event is being sent.
        /// </summary>
        [Display(Name = nameof(ModelsResources.RES_Display_WebhooksEventLog_Subscriber), ResourceType = typeof(ModelsResources))]
        [JsonPropertyName("subscriber")]
        [Required(AllowEmptyStrings = false, ErrorMessageResourceName = nameof(ModelsResources.RES_Validation_WebhooksEventLog_Subscriber_Required), ErrorMessageResourceType = typeof(ModelsResources))]
        public virtual string Subscriber
        {
            get;
            set;
        }

        #endregion

        #region Protected Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksEventLogBase"/> class.
        /// </summary>
        protected WebhooksEventLogBase()        
        {
            // Initialize default values

            this.SetDefaultValues();
        }

        #endregion

        #region Protected Methods

        /// <summary>
        /// Sets the default values.
        /// </summary>
        /// <remarks>
        /// This method should be overridden to set the default values of properties.
        /// </remarks>
        protected virtual void SetDefaultValues()
        {
        }

        #endregion

        #endregion
    }

    /// <summary>
    /// WebhooksEvent send log.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial class WebhooksEventLog : WebhooksEventLogBase
    {
        #region Code

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhooksEventLog"/> class.
        /// </summary>
        public WebhooksEventLog()        
            : base()
        {
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
