//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Globalization;
using System.Resources;

namespace Primavera.Lithium.Faturacao.Models
{
    #region Code

    #region Public Classes

    /// <summary>
    /// Provides means to access resource strings.
    /// </summary>
    [GeneratedCode("Lithium", "2.0")]
    public partial class ModelsResources
    {
        #region Code

        #region Fields

        private static ResourceManager fieldResourceManager;
        private static CultureInfo fieldResourceCulture;

        #endregion

        #region Public Properties

        /// <summary>
        /// Gets the RES_Display_Invoice_Amount resource string.
        /// </summary>
        public static string RES_Display_Invoice_Amount
        {
            get
            {
                return ResourceManager.GetString("RES_Display_Invoice_Amount", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_Invoice_Amount_Required resource string.
        /// </summary>
        public static string RES_Validation_Invoice_Amount_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_Invoice_Amount_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_Invoice_Id resource string.
        /// </summary>
        public static string RES_Display_Invoice_Id
        {
            get
            {
                return ResourceManager.GetString("RES_Display_Invoice_Id", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksEvent_Description resource string.
        /// </summary>
        public static string RES_Display_WebhooksEvent_Description
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksEvent_Description", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksEvent_Description_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksEvent_Description_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksEvent_Description_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksEvent_Event resource string.
        /// </summary>
        public static string RES_Display_WebhooksEvent_Event
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksEvent_Event", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksEvent_Event_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksEvent_Event_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksEvent_Event_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksEvent_Product resource string.
        /// </summary>
        public static string RES_Display_WebhooksEvent_Product
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksEvent_Product", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksEvent_Product_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksEvent_Product_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksEvent_Product_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksEvent_RequiredScope resource string.
        /// </summary>
        public static string RES_Display_WebhooksEvent_RequiredScope
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksEvent_RequiredScope", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksEvent_RequiredScope_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksEvent_RequiredScope_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksEvent_RequiredScope_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksSubscription_Event resource string.
        /// </summary>
        public static string RES_Display_WebhooksSubscription_Event
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksSubscription_Event", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksSubscription_Event_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksSubscription_Event_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksSubscription_Event_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksSubscription_NotificationEndpoint resource string.
        /// </summary>
        public static string RES_Display_WebhooksSubscription_NotificationEndpoint
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksSubscription_NotificationEndpoint", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksSubscription_NotificationEndpoint_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksSubscription_NotificationEndpoint_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksSubscription_NotificationEndpoint_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksSubscription_Product resource string.
        /// </summary>
        public static string RES_Display_WebhooksSubscription_Product
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksSubscription_Product", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksSubscription_Product_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksSubscription_Product_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksSubscription_Product_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksSubscription_Subscriber resource string.
        /// </summary>
        public static string RES_Display_WebhooksSubscription_Subscriber
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksSubscription_Subscriber", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksSubscription_Subscriber_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksSubscription_Subscriber_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksSubscription_Subscriber_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksSubscriptionDto_Events resource string.
        /// </summary>
        public static string RES_Display_WebhooksSubscriptionDto_Events
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksSubscriptionDto_Events", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksSubscriptionDto_Events_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksSubscriptionDto_Events_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksSubscriptionDto_Events_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksSubscriptionDto_NotificationEndpoint resource string.
        /// </summary>
        public static string RES_Display_WebhooksSubscriptionDto_NotificationEndpoint
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksSubscriptionDto_NotificationEndpoint", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksSubscriptionDto_NotificationEndpoint_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksSubscriptionDto_NotificationEndpoint_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksSubscriptionDto_NotificationEndpoint_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksSubscriptionDto_Product resource string.
        /// </summary>
        public static string RES_Display_WebhooksSubscriptionDto_Product
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksSubscriptionDto_Product", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksSubscriptionDto_Product_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksSubscriptionDto_Product_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksSubscriptionDto_Product_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksSubscriptionDto_Subscriber resource string.
        /// </summary>
        public static string RES_Display_WebhooksSubscriptionDto_Subscriber
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksSubscriptionDto_Subscriber", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksSubscriptionDto_Subscriber_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksSubscriptionDto_Subscriber_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksSubscriptionDto_Subscriber_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksEventLog_Attempts resource string.
        /// </summary>
        public static string RES_Display_WebhooksEventLog_Attempts
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksEventLog_Attempts", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksEventLog_Event resource string.
        /// </summary>
        public static string RES_Display_WebhooksEventLog_Event
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksEventLog_Event", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksEventLog_Event_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksEventLog_Event_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksEventLog_Event_Required", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Display_WebhooksEventLog_Subscriber resource string.
        /// </summary>
        public static string RES_Display_WebhooksEventLog_Subscriber
        {
            get
            {
                return ResourceManager.GetString("RES_Display_WebhooksEventLog_Subscriber", Culture);
            }
        }

        /// <summary>
        /// Gets the RES_Validation_WebhooksEventLog_Subscriber_Required resource string.
        /// </summary>
        public static string RES_Validation_WebhooksEventLog_Subscriber_Required
        {
            get
            {
                return ResourceManager.GetString("RES_Validation_WebhooksEventLog_Subscriber_Required", Culture);
            }
        }

        #endregion

        #region Internal Properties

        /// <summary>
        /// Gets the resource manager.
        /// </summary>
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (fieldResourceManager == null)
                {
                    fieldResourceManager = new ResourceManager("Primavera.Lithium.Faturacao.Models.GeneratedCode.ModelsResources.gen", typeof(ModelsResources).Assembly);
                }
                
                return fieldResourceManager;
            }
        }

        /// <summary>
        /// Gets or sets the culture.
        /// </summary>
        internal static CultureInfo Culture
        {
            get
            {
                return fieldResourceCulture;
            }
            set
            {
                fieldResourceCulture = value;
            }
        }

        #endregion

        #region Public Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsResources"/> class.
        /// </summary>
        public ModelsResources()        
        {
        }

        #endregion

        #endregion
    }

    #endregion

    #endregion
}
